config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :employees do
    resources :time_entries
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :account_entries, dependent: :destroy

	validates :name, presence: true, 
					 length: {in: 1..70, message: %Q|Please enter decent name Sr.|},
					 uniqueness: true

	def update_balance!
		update_attributes(
			balance: self.account_entries.approved.sum(:amount)
		)
	end
end

app/models/account_entry.rb
class AccountEntry < ActiveRecord::Base
	has_paper_trail
	belongs_to :account

	validates :account_id, presence: true
	validates_associated :account

	after_save :update_account_balance!, :if => :approved?

	scope :approved, -> { with_state(:approved) }

	state_machine :state, :initial => :submitted do
		event :approve do
			transition :submitted => :approved
		end
		event :reject do
			transition :submitted => :rejected
		end
	end

end

app/models/customer.rb
class Customer < Account
	has_paper_trail
	has_many :time_entries
	#scope :premier, -> { where("employees > ?", 1)}
	scope :newest, -> { order("created_at DESC") }
	scope :starts_with, -> (letter) { where("name LIKE ?", letter + "%") }
end

app/models/employee.rb
class Employee < Account
	has_many :time_entries
	has_and_belongs_to_many :projects, :join_table => "employees_projects"
	def total_hours
		time_entries.sum(:time)
	end

	def log_time amount, customer
		TimeEntry.create(time: amount, employee: self, account: customer)
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :customer
	has_and_belongs_to_many :employees, :join_table => "employees_projects"

	validates :name, presence: true, length: {in: 1..70}
end

app/models/time_entry.rb
class TimeEntry < AccountEntry
	belongs_to :employee

	validates :time, numericality: {greater_than: 0, less_than: 24}
	
	before_create :calculate_amount!
	after_save :update_account_balance!

	def self.per_hour
		100
	end

	def calculate_amount!
		self.amount = TimeEntry.per_hour * self.time
	end

	def update_account_balance!
		account.update_balance!
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		@accounts = Customer.all
	end

	def show
		@account = Account.find(params[:id])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.all
	end

	def show
		@employee = Employee.find(params[:id])
	end

	def create
		@employee = Employee.new(params.require(:employee).permit(:name))
		if @employee.save
			flash[:success] = %Q|Added employee|
			redirect_to employees_path
		else
			flash[:error] = %Q|There was a problem adding employee|
			redirect_to employees_path
		end
	end
end
	

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def create
		e = Employee.find(params[:employee_id])
		e.time_entries.create(params.require(:time_entry).permit(:time, :account_id))
  		redirect_to employee_path(e)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/accounts/index.html.erb
<table>
	<% @accounts.each do |account| %>
	<tr>
		<td><%= link_to account.name, account_path(account) %></td>
		<td><%= account.type.to_s %></td>
	</tr>
	<% end %>
</table>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

Total Hours: <%= @account.account_entries.sum(:time) %>
Balance: <%= @account.balance %>

<h4>Account Entries</h4>

<table>
	<% @account.account_entries.each do |entry| %>
	<tr>
		<td><%= entry.created_at %></td>
		<td><%= entry.employee.name %></td>
		<td><%= entry.time %> hours</td>
	</tr>
	<% end %>
</table>

app/views/employees/index.html.erb
<% @employees.each do |employee| %>
	<%= link_to employee.name, employee_path(employee) %>
<% end %>

<%= form_for Employee.new do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>

<h3>Submit time form</h3>
<%= form_for [@employee, TimeEntry.new] do |f| %>
	<%= f.label :customer %>
	<%= f.collection_select(:account_id,Customer.all, :id, :name) %>
	<%= f.label :time %>
	<%= f.text_field :time, :value => 1.0 %>
	<%= f.submit %>
<% end %>

<h3>Time Entries</h3>

<% @employee.time_entries.each do |entry| %>
	<div class="entry">
		<strong><%= entry.state %></strong>
		<%= entry.time %>
		<%= entry.account.name %>
		<%= entry.created_at %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |type, message| %>

		<div class="alert flash <%= type %>">
			<%= message %>
		</div>
	<% end %>
<%= yield %>

</body>
</html>